/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWithdrawRouteImport } from './routes/_app.withdraw'
import { Route as AppWatchlistRouteImport } from './routes/_app.watchlist'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppRecurringRouteImport } from './routes/_app.recurring'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppNewsRouteImport } from './routes/_app.news'
import { Route as AppMarketsRouteImport } from './routes/_app.markets'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBanksRouteImport } from './routes/_app.banks'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppDepositIndexRouteImport } from './routes/_app.deposit.index'
import { Route as ApiPublicPricesRouteImport } from './routes/api/public/prices'
import { Route as AppSellSymbolRouteImport } from './routes/_app.sell.$symbol'
import { Route as AppDepositCryptoRouteImport } from './routes/_app.deposit.crypto'
import { Route as AppDepositCardRouteImport } from './routes/_app.deposit.card'
import { Route as AppBuySymbolRouteImport } from './routes/_app.buy.$symbol'
import { Route as AppAssetSymbolRouteImport } from './routes/_app.asset.$symbol'
import { Route as AppAdminWithdrawalsRouteImport } from './routes/_app.admin.withdrawals'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminDepositsRouteImport } from './routes/_app.admin.deposits'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBanksRoute = AppBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositIndexRoute = AppDepositIndexRouteImport.update({
  id: '/deposit/',
  path: '/deposit/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicPricesRoute = ApiPublicPricesRouteImport.update({
  id: '/api/public/prices',
  path: '/api/public/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSellSymbolRoute = AppSellSymbolRouteImport.update({
  id: '/sell/$symbol',
  path: '/sell/$symbol',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositCryptoRoute = AppDepositCryptoRouteImport.update({
  id: '/deposit/crypto',
  path: '/deposit/crypto',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositCardRoute = AppDepositCardRouteImport.update({
  id: '/deposit/card',
  path: '/deposit/card',
  getParentRoute: () => AppRoute,
} as any)
const AppBuySymbolRoute = AppBuySymbolRouteImport.update({
  id: '/buy/$symbol',
  path: '/buy/$symbol',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetSymbolRoute = AppAssetSymbolRouteImport.update({
  id: '/asset/$symbol',
  path: '/asset/$symbol',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminWithdrawalsRoute = AppAdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDepositsRoute = AppAdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/banks': typeof AppBanksRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/history': typeof AppHistoryRoute
  '/markets': typeof AppMarketsRoute
  '/news': typeof AppNewsRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile': typeof AppProfileRoute
  '/recurring': typeof AppRecurringRoute
  '/search': typeof AppSearchRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/watchlist': typeof AppWatchlistRoute
  '/withdraw': typeof AppWithdrawRoute
  '/admin/deposits': typeof AppAdminDepositsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/asset/$symbol': typeof AppAssetSymbolRoute
  '/buy/$symbol': typeof AppBuySymbolRoute
  '/deposit/card': typeof AppDepositCardRoute
  '/deposit/crypto': typeof AppDepositCryptoRoute
  '/sell/$symbol': typeof AppSellSymbolRoute
  '/api/public/prices': typeof ApiPublicPricesRoute
  '/deposit/': typeof AppDepositIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/banks': typeof AppBanksRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/history': typeof AppHistoryRoute
  '/markets': typeof AppMarketsRoute
  '/news': typeof AppNewsRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile': typeof AppProfileRoute
  '/recurring': typeof AppRecurringRoute
  '/search': typeof AppSearchRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/watchlist': typeof AppWatchlistRoute
  '/withdraw': typeof AppWithdrawRoute
  '/admin/deposits': typeof AppAdminDepositsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/asset/$symbol': typeof AppAssetSymbolRoute
  '/buy/$symbol': typeof AppBuySymbolRoute
  '/deposit/card': typeof AppDepositCardRoute
  '/deposit/crypto': typeof AppDepositCryptoRoute
  '/sell/$symbol': typeof AppSellSymbolRoute
  '/api/public/prices': typeof ApiPublicPricesRoute
  '/deposit': typeof AppDepositIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/banks': typeof AppBanksRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/markets': typeof AppMarketsRoute
  '/_app/news': typeof AppNewsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/recurring': typeof AppRecurringRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/watchlist': typeof AppWatchlistRoute
  '/_app/withdraw': typeof AppWithdrawRoute
  '/_app/admin/deposits': typeof AppAdminDepositsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/_app/asset/$symbol': typeof AppAssetSymbolRoute
  '/_app/buy/$symbol': typeof AppBuySymbolRoute
  '/_app/deposit/card': typeof AppDepositCardRoute
  '/_app/deposit/crypto': typeof AppDepositCryptoRoute
  '/_app/sell/$symbol': typeof AppSellSymbolRoute
  '/api/public/prices': typeof ApiPublicPricesRoute
  '/_app/deposit/': typeof AppDepositIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/welcome'
    | '/account'
    | '/admin'
    | '/banks'
    | '/dashboard'
    | '/documents'
    | '/history'
    | '/markets'
    | '/news'
    | '/notifications'
    | '/orders'
    | '/portfolio'
    | '/profile'
    | '/recurring'
    | '/search'
    | '/security'
    | '/settings'
    | '/watchlist'
    | '/withdraw'
    | '/admin/deposits'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/asset/$symbol'
    | '/buy/$symbol'
    | '/deposit/card'
    | '/deposit/crypto'
    | '/sell/$symbol'
    | '/api/public/prices'
    | '/deposit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/welcome'
    | '/account'
    | '/admin'
    | '/banks'
    | '/dashboard'
    | '/documents'
    | '/history'
    | '/markets'
    | '/news'
    | '/notifications'
    | '/orders'
    | '/portfolio'
    | '/profile'
    | '/recurring'
    | '/search'
    | '/security'
    | '/settings'
    | '/watchlist'
    | '/withdraw'
    | '/admin/deposits'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/asset/$symbol'
    | '/buy/$symbol'
    | '/deposit/card'
    | '/deposit/crypto'
    | '/sell/$symbol'
    | '/api/public/prices'
    | '/deposit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/welcome'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/banks'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/history'
    | '/_app/markets'
    | '/_app/news'
    | '/_app/notifications'
    | '/_app/orders'
    | '/_app/portfolio'
    | '/_app/profile'
    | '/_app/recurring'
    | '/_app/search'
    | '/_app/security'
    | '/_app/settings'
    | '/_app/watchlist'
    | '/_app/withdraw'
    | '/_app/admin/deposits'
    | '/_app/admin/users'
    | '/_app/admin/withdrawals'
    | '/_app/asset/$symbol'
    | '/_app/buy/$symbol'
    | '/_app/deposit/card'
    | '/_app/deposit/crypto'
    | '/_app/sell/$symbol'
    | '/api/public/prices'
    | '/_app/deposit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicPricesRoute: typeof ApiPublicPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/withdraw': {
      id: '/_app/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring': {
      id: '/_app/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets': {
      id: '/_app/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banks': {
      id: '/_app/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof AppBanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposit/': {
      id: '/_app/deposit/'
      path: '/deposit'
      fullPath: '/deposit/'
      preLoaderRoute: typeof AppDepositIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/prices': {
      id: '/api/public/prices'
      path: '/api/public/prices'
      fullPath: '/api/public/prices'
      preLoaderRoute: typeof ApiPublicPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sell/$symbol': {
      id: '/_app/sell/$symbol'
      path: '/sell/$symbol'
      fullPath: '/sell/$symbol'
      preLoaderRoute: typeof AppSellSymbolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposit/crypto': {
      id: '/_app/deposit/crypto'
      path: '/deposit/crypto'
      fullPath: '/deposit/crypto'
      preLoaderRoute: typeof AppDepositCryptoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposit/card': {
      id: '/_app/deposit/card'
      path: '/deposit/card'
      fullPath: '/deposit/card'
      preLoaderRoute: typeof AppDepositCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buy/$symbol': {
      id: '/_app/buy/$symbol'
      path: '/buy/$symbol'
      fullPath: '/buy/$symbol'
      preLoaderRoute: typeof AppBuySymbolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asset/$symbol': {
      id: '/_app/asset/$symbol'
      path: '/asset/$symbol'
      fullPath: '/asset/$symbol'
      preLoaderRoute: typeof AppAssetSymbolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/withdrawals': {
      id: '/_app/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AppAdminWithdrawalsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/deposits': {
      id: '/_app/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AppAdminDepositsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminDepositsRoute: typeof AppAdminDepositsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminWithdrawalsRoute: typeof AppAdminWithdrawalsRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminDepositsRoute: AppAdminDepositsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminWithdrawalsRoute: AppAdminWithdrawalsRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBanksRoute: typeof AppBanksRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppNewsRoute: typeof AppNewsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppAssetSymbolRoute: typeof AppAssetSymbolRoute
  AppBuySymbolRoute: typeof AppBuySymbolRoute
  AppDepositCardRoute: typeof AppDepositCardRoute
  AppDepositCryptoRoute: typeof AppDepositCryptoRoute
  AppSellSymbolRoute: typeof AppSellSymbolRoute
  AppDepositIndexRoute: typeof AppDepositIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBanksRoute: AppBanksRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppNewsRoute: AppNewsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppSearchRoute: AppSearchRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppAssetSymbolRoute: AppAssetSymbolRoute,
  AppBuySymbolRoute: AppBuySymbolRoute,
  AppDepositCardRoute: AppDepositCardRoute,
  AppDepositCryptoRoute: AppDepositCryptoRoute,
  AppSellSymbolRoute: AppSellSymbolRoute,
  AppDepositIndexRoute: AppDepositIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicPricesRoute: ApiPublicPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
