import metamaskAsset from "@/assets/metamask.png.asset.json";
import fetchaiAsset from "@/assets/fetchai.png.asset.json";

export const walletImages: Record<string, string> = {
  "WalletConnect": "https://images.seeklogo.com/logo-png/43/2/walletconnect-logo-png_seeklogo-430923.png",
  "Bifrost Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0INqtV6c7kG6-YE8C1SA1EnGEukDxyGpbdg&s",
  "Ledger Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGEO2EwcAKY5OS5RndSkuXkLy0cSmiWbXF3w&s",
  "Xaman Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz-Jef6YHm7AMykPQPtUhVj3LzZw9RIL01Ug&s",
  "MetaMask": metamaskAsset.url,
  "Exodus": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7ac9O_DORRUoTuI9KIR-wAHGYJOEOoDLvkA&s",
  "Uniswap Wallet": "https://cryptologos.cc/logos/uniswap-uni-logo.png",
  "Polkadot Wallet": "https://s3.amazonaws.com/appforest_uf/f1670595972292x285725902843603870/polkadot.png",
  "HashPack Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLtobBLVml7yGPBbfO40Orw7HDP82X1a4z9Q&s",
  "BankSocial Wallet": "https://play-lh.googleusercontent.com/YvPFT4XObRxzXY548vEYYWU99vuNXEYTlNzO3IxMl55bpxJttQyYuxNXFQp_AjhuWyE=w240-h480-rw",
  "Binance Smart Chain": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG89viNFBqmyhkyCO4W2UHVF-NV5Qn6AtTzg&s",
  "SafePal Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1CDl_6EEhHjnYVuchge5oqOY1BJ7pJy9CBg&s",
  "Fetch.ai Wallet": fetchaiAsset.url,
  "Bifrost wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0INqtV6c7kG6-YE8C1SA1EnGEukDxyGpbdg&s",
  "Ledger Live": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGEO2EwcAKY5OS5RndSkuXkLy0cSmiWbXF3w&s",
  "Zerion Wallet": "https://play-lh.googleusercontent.com/lxl3CQLYmbY7kHtMn3ehz06ebEIIxYOETf8hlWPNW6L3ZPxuhSrnIq-4k5T89gd4gA=w240-h480-rw",
  "OKX Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnI5O0sf4FKYntQKmTjB-lqzZzk62i56tEtw&s",
  "Shido Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQwL7dScQM2vy305xJ0rNnmK_JOGU1502stw&s",
  "XUMM Wallet": "https://pbs.twimg.com/profile_images/1280832346611167236/1sQA2Dn9_400x400.jpg",
  "Coinbase Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuFM2QKaMfn5Z1n9jUMg3wySi_Cu1Ive_oQ&s",
  "GateWeb3 Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4SNWaMtw0fcFHSrIP3cXOvYLy7oCPzZd5VA&s",
  "BitGet Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHDRiyge4nb31LvRpRnGXs61sboMpUU42A0A&s",
  "Robinhood Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRi-utj1AxLkrVVq6QdFvQ3yJpbzZB7CJdQ9w&s",
  "ByBit Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjLWTFWl72vwBZexad4NNb43adzoBgwJzdTQ&s",
  "Frontier Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnl0Kfg98JmFU2eas2v_isa0zDQ2bUK9f7SQ&s",
  "Grove Wallet": "https://play-lh.googleusercontent.com/3xNUjrDJbGpFOCsgYt1xoSz4vCiPwP4uDQDzf1nbbcZ7Ppmqagog19zxyY6HrdlKHnGm",
  "SafeMoon Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW9q389DOBbwed1jvG7rtdNSDFihBWBmUB2g&s",
  "SaitaPro Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHS4lEcOrUYO9edmLb_sSxf0shnBkFoJpqYw&s",
  "Phantom Wallet": "https://coinlaunch.space/media/images/4/8/5/0/4850.sp3ow1.192x192.png",
  "Enjin Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJp7OdVKqTUh5yn3N7nIF2I8quC6Yf956m6A&s",
  "Blockchain Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBOLM2CK9o8CE4cxr6gU0dFM3HyxCer3ryvA&s",
  "MEW Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaoWPuhrzC1LHvEtqxUQvMotXF7gQVdfvYCw&s",
  "Rabby Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgLPW7LYjMqjb1cKrMneM1ZGnDse5T_3ionw&s",
  "BRISE Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMIamiHHc7wT8BhOnL1gAeHGn5e8NifAQWLg&s",
  "D'CENT Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdOkyIiexxX_dMtuO9lnKlfm9KBv4XDJay1A&s",
  "Rainbow": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv0n_AIQ_-oDHrqJ5byuJnyU-w4tC-ef2_6g&s",
  "Trust Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsBrpjUaDrS_CEdrg7km2_08t6ZXPDtg9Tpw&s",
  "Argent": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsHCOZuf4R7wqYUfT13h2O6kX8caxQzFpVQQ&s",
  "Gnosis Safe Multisig": "https://pbs.twimg.com/profile_images/1643941027898613760/gyhYEOCE_400x400.jpg",
  "Equal": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFIz77HrtFZ13pl-qvC-vzd1DeMO_UQ7PMqg&s",
  "MEET.ONE": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG930rep_MfTkNfNvqRTIhiBTQ43R_FvNbsA&s",
  "MoriX Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbIH0Fi2IB7IpXYGGA3W4TwNnqJOrUwBZAxg&s",
  "Brave Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgdDD7qlpvjPM_xWzYtijQFuob8pSo5dHaYw&s",
  "Venly Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrYIMVsVLhf_Shi9b4fOr6dV4dudVskvejYA&s",
  "Crypto.com | DeFi Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8UiMc9LaKjvdZ9BlHD32dlWEAAIq3hMkxTw&s",
  "Pillar": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo9hWKPD2BcQge-LfI6cVT1AxwRVYkjC5UdA&s",
  "imToken": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrTcHlP2Tf6rNVXxDywaxrGP7gd33L9HZ1Og&s",
  "ONTO": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_P7Fh3FqxWd-iztJnDaQ1z3uE1q-LaGOouA&s",
  "TokenPocket": "https://play-lh.googleusercontent.com/hcnLVaagPA_c8TGRDtV4c3R7mkhw3pAlop1WI4zJjjokJ5DErElAqwqkYriYmRRCaaY",
  "MathWallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN04hBJLqwxe0dndDvoSMn4JJeyklXMEQ-ag&s",
  "BitPay": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwjHfvlPbNzTAJ6Guz6VXnpN6rG0UdJfgVnA&s",
  "Walleth": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT7cU8fY2vMznsXToh67Xs1IilWCGplHaa5w&s",
  "Authereum": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpyRTZ9ADJMLMnYB0JyLAl4WOkOZdbg55iZQ&s",
  "Dharma": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxb6tu2SHXyiYzt7r8G2Q6HLfO2xdo1GVgJQ&s",
  "1inch Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdJiTQw1533oqnEgpeejsEIHM6WVz169hlEA&s",
  "Huobi Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaleIiDrpBlhDC_0JmIthi6aul0_ZAZyaXnw&s",
  "Eidoo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRixCLlWUdvEKW4pyvW1jjfUtnrCMpvg1ZRVA&s",
  "MYKEY": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvIGz1XAS_B2Q5hgjCbFevVZMNbXfMKnB-mg&s",
  "Loopring Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2OQJIGBnucFy0sjgDwcbvZGwzlkGS_z3iuA&s",
  "TrustVault": "https://media.licdn.com/dms/image/v2/D4E0BAQGiLqp0WUtxbg/company-logo_200_200/B4EZYbMcS3GYAI-/0/1744212969046/trustvaultofficial_logo?e=2147483647&v=beta&t=w2QAUiYFAaUN2qK5ESsgXmOdVUix67njtxVCTb-Xn6s",
  "Tangem Wallet": "https://images.crunchbase.com/image/upload/c_pad,f_auto,q_auto:eco,dpr_1/a5r5vnxlpb0aj4nvmcpd?ik-sanitizeSvg=true",
};

export const allWallets = [
  "MetaMask", "Exodus", "Ledger Wallet", "Uniswap Wallet", "Polkadot Wallet",
  "HashPack Wallet", "BankSocial Wallet", "Binance Smart Chain", "SafePal Wallet",
  "Fetch.ai Wallet", "Bifrost wallet", "Ledger Live", "Zerion Wallet",
  "OKX Wallet", "Shido Wallet", "XUMM Wallet", "Coinbase Wallet",
  "GateWeb3 Wallet", "BitGet Wallet", "Robinhood Wallet", "ByBit Wallet",
  "Frontier Wallet", "Grove Wallet", "SafeMoon Wallet", "SaitaPro Wallet",
  "Phantom Wallet", "Enjin Wallet", "Blockchain Wallet", "MEW Wallet",
  "Xaman Wallet", "Rabby Wallet", "BRISE Wallet", "D'CENT Wallet",
  "Rainbow", "Trust Wallet", "Argent", "Tangem Wallet",
  "Gnosis Safe Multisig", "Equal", "MEET.ONE", "MoriX Wallet",
  "Brave Wallet", "Venly Wallet", "Crypto.com | DeFi Wallet", "Pillar",
  "imToken", "ONTO", "TokenPocket", "MathWallet",
  "BitPay", "Walleth", "Authereum", "Dharma",
  "1inch Wallet", "Huobi Wallet", "Eidoo", "MYKEY",
  "Loopring Wallet", "TrustVault",
];

export const getWalletImage = (wallet: string): string => {
  return walletImages[wallet] || "";
};
